### ISSUE TITLE
react-dom

### ISSUE THREAD

**Issue by serusko** [HasanAyan/craco-plugin-react-hot-reload#2]
as first, good job with this plugin
but i have one feature-proposal

regarding this https://github.com/gaearon/react-hot-loader#react--dom
it would be nice to have webpack alias for dev mode to avoid console warning

`React-Hot-Loader: react-🔥-dom patch is not detected. React 16.6+ features may not work.`

so please add alias for react-hot-dom in dev mode (maybe i will do)
but, maybe it needs some inspection because I'm not sure how to resolve proper react-dom version (how this `@hot-loader/react-dom` works)

**Comment by rot1024** [comment]
+1

**Comment by RXminuS** [comment]
+5 please merge this :-)

**Comment by theKashey** [comment]
The best way is to use power of `craco` to add a webpack plugin to patch `react-dom`
> Webpack plugin will also land a "hot" patch to react-dom (probably this string is not easy to find)

**Comment by hasanayan** [comment]
Guys, sorry for not reacting to this. I wasn’t able to take care of it due to some personal issues.

I can’t review it but I’ll go ahead and merge it. But since I did not set up a release pipeline, I’m not sure how to update the npm package on my iphone. Any suggestions?

**Comment by hasanayan** [comment]
everything should be fine now.
